<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>C3DPlugin</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>x64</Platforms>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoCAD.NET" Version="25.1.0" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="acdbmgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\acdbmgd.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="acmgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\acmgd.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="AeccDbMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\C3D\AeccDbMgd.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="AeccPressurePipesMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\C3D\AeccPressurePipesMgd.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="AecBaseMgd">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\ACA\AecBaseMgd.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="CaMgdContentData">
			<HintPath>C:\Program Files\Autodesk\AutoCAD 2026\C3D\CaMgdContentData.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<Compile Update="myCommands.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>myCommands.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="myCommands.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>myCommands.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>
</Project>
